require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe IngredientTypesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # IngredientType. As you add validations to IngredientType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IngredientTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ingredient_types as @ingredient_types" do
      ingredient_type = IngredientType.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ingredient_types)).to eq([ingredient_type])
    end
  end

  describe "GET show" do
    it "assigns the requested ingredient_type as @ingredient_type" do
      ingredient_type = IngredientType.create! valid_attributes
      get :show, {:id => ingredient_type.to_param}, valid_session
      expect(assigns(:ingredient_type)).to eq(ingredient_type)
    end
  end

  describe "GET new" do
    it "assigns a new ingredient_type as @ingredient_type" do
      get :new, {}, valid_session
      expect(assigns(:ingredient_type)).to be_a_new(IngredientType)
    end
  end

  describe "GET edit" do
    it "assigns the requested ingredient_type as @ingredient_type" do
      ingredient_type = IngredientType.create! valid_attributes
      get :edit, {:id => ingredient_type.to_param}, valid_session
      expect(assigns(:ingredient_type)).to eq(ingredient_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IngredientType" do
        expect {
          post :create, {:ingredient_type => valid_attributes}, valid_session
        }.to change(IngredientType, :count).by(1)
      end

      it "assigns a newly created ingredient_type as @ingredient_type" do
        post :create, {:ingredient_type => valid_attributes}, valid_session
        expect(assigns(:ingredient_type)).to be_a(IngredientType)
        expect(assigns(:ingredient_type)).to be_persisted
      end

      it "redirects to the created ingredient_type" do
        post :create, {:ingredient_type => valid_attributes}, valid_session
        expect(response).to redirect_to(IngredientType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ingredient_type as @ingredient_type" do
        post :create, {:ingredient_type => invalid_attributes}, valid_session
        expect(assigns(:ingredient_type)).to be_a_new(IngredientType)
      end

      it "re-renders the 'new' template" do
        post :create, {:ingredient_type => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ingredient_type" do
        ingredient_type = IngredientType.create! valid_attributes
        put :update, {:id => ingredient_type.to_param, :ingredient_type => new_attributes}, valid_session
        ingredient_type.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ingredient_type as @ingredient_type" do
        ingredient_type = IngredientType.create! valid_attributes
        put :update, {:id => ingredient_type.to_param, :ingredient_type => valid_attributes}, valid_session
        expect(assigns(:ingredient_type)).to eq(ingredient_type)
      end

      it "redirects to the ingredient_type" do
        ingredient_type = IngredientType.create! valid_attributes
        put :update, {:id => ingredient_type.to_param, :ingredient_type => valid_attributes}, valid_session
        expect(response).to redirect_to(ingredient_type)
      end
    end

    describe "with invalid params" do
      it "assigns the ingredient_type as @ingredient_type" do
        ingredient_type = IngredientType.create! valid_attributes
        put :update, {:id => ingredient_type.to_param, :ingredient_type => invalid_attributes}, valid_session
        expect(assigns(:ingredient_type)).to eq(ingredient_type)
      end

      it "re-renders the 'edit' template" do
        ingredient_type = IngredientType.create! valid_attributes
        put :update, {:id => ingredient_type.to_param, :ingredient_type => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ingredient_type" do
      ingredient_type = IngredientType.create! valid_attributes
      expect {
        delete :destroy, {:id => ingredient_type.to_param}, valid_session
      }.to change(IngredientType, :count).by(-1)
    end

    it "redirects to the ingredient_types list" do
      ingredient_type = IngredientType.create! valid_attributes
      delete :destroy, {:id => ingredient_type.to_param}, valid_session
      expect(response).to redirect_to(ingredient_types_url)
    end
  end

end
